name: PR
on:
  pull_request:
jobs:
  pr:
    name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: gems-
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build website
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install
          bundle exec jekyll build -tV
